import { createAsyncThunk, createSlice, PayloadAction } from '@reduxjs/toolkit';
import { RootState } from '../store';
import { Floor } from '@/interfaces/sanctum';
import { setRegion } from './regionSlice';
import { fetchSanctum } from '@/lib/fetchData';

// value: area key -> floors, each floor being an array of its difficulty variants.
type SanctumData = { [area: string]: Floor[][] };

export interface SanctumState {
  value: SanctumData;
  status: 'idle' | 'loading' | 'failed';
  floorData?: Floor;
  activeArea: string;
  activeFloor: number;
  activeDiff: number;
}

const initialState: SanctumState = {
  value: {},
  status: 'loading',
  activeArea: "EW01",
  activeFloor: 0,
  activeDiff: 0,
};

// Clamp the active indices to what `value` actually contains and return the
// matching Floor (or undefined if the area/floor/diff isn't present). Mutates
// the (Immer draft) state's active* fields so they stay in range.
function selectAndClamp(state: SanctumState): Floor | undefined {
  const floors = state.value[state.activeArea];
  if (!floors || floors.length === 0) return undefined;
  if (state.activeFloor >= floors.length) state.activeFloor = floors.length - 1;
  if (state.activeFloor < 0) state.activeFloor = 0;

  const diffs = floors[state.activeFloor];
  if (!diffs || diffs.length === 0) return undefined;
  if (state.activeDiff >= diffs.length) state.activeDiff = diffs.length - 1;
  if (state.activeDiff < 0) state.activeDiff = 0;

  const floor = diffs[state.activeDiff];
  return floor ? { ...floor } : undefined;
}

export const fetchSanctumAsync = createAsyncThunk<SanctumData, void, {state: RootState}>(
  'sanctum/fetch',
  async function (_, thunkApi)  {
    if (thunkApi.getState().sanctum.status == "failed") return {}
    else if (Object.keys(thunkApi.getState().sanctum.value).length > 0) {
      return thunkApi.getState().sanctum.value
    }
    else {
      try {
        const response = await fetchSanctum(thunkApi.getState().region.region)
        return response ? response : {}
      }
      catch {
        return thunkApi.rejectWithValue({})
      }
    }
  }
);

export const sanctumSlice = createSlice({
  name: 'sanctum',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    setArea: (state, action: PayloadAction<string>) => {
      state.activeArea = action.payload;
      state.floorData = selectAndClamp(state);
    },
    setFloor: (state, action: PayloadAction<number>) => {
      state.activeFloor = action.payload;
      state.floorData = selectAndClamp(state);
    },
    setDiff: (state, action: PayloadAction<number>) => {
      state.activeDiff = action.payload;
      state.floorData = selectAndClamp(state);
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(fetchSanctumAsync.pending, (state) => {
        state.status = 'loading';
      })
      .addCase(fetchSanctumAsync.fulfilled, (state, action) => {
        state.value = action.payload;
        state.status = 'idle';
        state.floorData = selectAndClamp(state);
      })
      .addCase(fetchSanctumAsync.rejected, (state, action) => {
        state.value = {};
        state.status = 'failed';
      })
      .addCase(setRegion, (state) => {
        state.value = {};
        state.status = 'loading';
        state.floorData = undefined;
        state.activeFloor = 0;
        state.activeDiff = 0;
      })
  },
});

export const { setArea, setDiff, setFloor } = sanctumSlice.actions;

export const selectSanctum = (state: RootState) => state.sanctum.value;
export const selectSanctumStatus = (state: RootState) => state.sanctum.status;
export const selectFloorData = (state: RootState) => state.sanctum.floorData;
export const selectActiveArea = (state: RootState) => state.sanctum.activeArea;
export const selectActiveFloor = (state: RootState) => state.sanctum.activeFloor;
export const selectActiveDiff = (state: RootState) => state.sanctum.activeDiff;

export default sanctumSlice.reducer;