import { createAsyncThunk, createSlice, isRejectedWithValue, PayloadAction } from '@reduxjs/toolkit';
import { RootState, AppThunk } from '../store';
import { Floor } from '@/interfaces/sanctum';

export interface WorldState {
  value: {[key: string]: Floor[][]};
  imagelink: {[key: string]: string};
  status: 'idle' | 'loading' | 'failed';
}

const initialState: WorldState = {
  value: {},
  imagelink: {},
  status: 'idle',
};

export const fetchSanctumAsync = createAsyncThunk<{[key: string]: Floor[][]}, void, {state: RootState}>(
  'sanctum/fetch',
  async function (_, thunkApi)  {
    if (thunkApi.getState().sanctum.status == "failed") return {}
    else if (Object.keys(thunkApi.getState().sanctum.value).length > 0) {
      return thunkApi.getState().sanctum.value
    }
    else {
      try {
        const response = await fetch("/api/sanctum").then(res => res.json())
        return response ? response : {}
      }
      catch {
        return thunkApi.rejectWithValue({})
      }
    }
  }
);

export const sanctumSlice = createSlice({
  name: 'world',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {

  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(fetchSanctumAsync.pending, (state) => {
        state.status = 'loading';
      })
      .addCase(fetchSanctumAsync.fulfilled, (state, action) => {
        state.value = action.payload;
      })
      .addCase(fetchSanctumAsync.rejected, (state, action) => {
        state.value = {};
        state.status = 'failed';
      })
  },
});

export const selectSanctum = (state: RootState) => state.sanctum.value;
export const selectSanctumStatus = (state: RootState) => state.sanctum.status;

export default sanctumSlice.reducer;